// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include <esp_now.h>

extern int8_t power[4];   // power for the selected loco, loco1, loco2, loco3
extern uint8_t targetAdress[]; // broadcast address

void stopAll(lv_event_t * e)
{
	for (int i=0; i<4; i++) {
		power[i] = 0;
	}
	  // Send message via ESP-NOW
  esp_err_t result = esp_now_send(targetAdress, (uint8_t *) &power, sizeof(power));

	hapticEffect(52); // strong pulse

}
