// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_Screen1;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_power = NULL;lv_obj_t *ui_Arc1 = NULL;lv_obj_t *ui_Arc2 = NULL;lv_obj_t *ui_Arc3 = NULL;lv_obj_t *ui_Arc4 = NULL;lv_obj_t *ui_power1 = NULL;lv_obj_t *ui_power2 = NULL;lv_obj_t *ui_power3 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Panel8 = NULL;lv_obj_t *ui_Panel9 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_Label9 = NULL;
// event funtions
void ui_event_Panel9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      stopAll( e );
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_power = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_power, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_power, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_power, -71 );
lv_obj_set_y( ui_power, 57 );
lv_obj_set_align( ui_power, LV_ALIGN_CENTER );
lv_label_set_text(ui_power,"76");
lv_obj_set_style_text_color(ui_power, lv_color_hex(0x9B9797), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_power, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_power, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arc1 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc1, 186);
lv_obj_set_height( ui_Arc1, 186);
lv_obj_set_x( ui_Arc1, -71 );
lv_obj_set_y( ui_Arc1, 0 );
lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Arc1, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_value(ui_Arc1, 0);
lv_obj_set_style_arc_width(ui_Arc1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0xDD67E4), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc1, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Arc1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Arc2 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc2, 110);
lv_obj_set_height( ui_Arc2, 110);
lv_obj_set_x( ui_Arc2, 109 );
lv_obj_set_y( ui_Arc2, 0 );
lv_obj_set_align( ui_Arc2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Arc2, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_value(ui_Arc2, 0);
lv_obj_set_style_arc_width(ui_Arc2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Arc2, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x40FFD7), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc2, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Arc2, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Arc2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Arc3 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc3, 110);
lv_obj_set_height( ui_Arc3, 110);
lv_obj_set_x( ui_Arc3, 43 );
lv_obj_set_y( ui_Arc3, -107 );
lv_obj_set_align( ui_Arc3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Arc3, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_value(ui_Arc3, 0);
lv_obj_set_style_arc_width(ui_Arc3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Arc3, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Arc3, lv_color_hex(0xFF407F), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc3, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Arc3, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Arc3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Arc3, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc3, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Arc4 = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc4, 110);
lv_obj_set_height( ui_Arc4, 110);
lv_obj_set_x( ui_Arc4, 43 );
lv_obj_set_y( ui_Arc4, 107 );
lv_obj_set_align( ui_Arc4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Arc4, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_arc_set_value(ui_Arc4, 0);
lv_obj_set_style_arc_width(ui_Arc4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Arc4, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Arc4, lv_color_hex(0x77BBEE), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc4, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc4, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Arc4, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Arc4, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Arc4, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc4, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_power1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_power1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_power1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_power1, 109 );
lv_obj_set_y( ui_power1, 35 );
lv_obj_set_align( ui_power1, LV_ALIGN_CENTER );
lv_label_set_text(ui_power1,"34");
lv_obj_set_style_text_color(ui_power1, lv_color_hex(0x9B9797), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_power1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_power1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_power2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_power2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_power2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_power2, 43 );
lv_obj_set_y( ui_power2, 140 );
lv_obj_set_align( ui_power2, LV_ALIGN_CENTER );
lv_label_set_text(ui_power2,"27");
lv_obj_set_style_text_color(ui_power2, lv_color_hex(0x9B9797), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_power2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_power2, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_power3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_power3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_power3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_power3, 43 );
lv_obj_set_y( ui_power3, -74 );
lv_obj_set_align( ui_power3, LV_ALIGN_CENTER );
lv_label_set_text(ui_power3,"72");
lv_obj_set_style_text_color(ui_power3, lv_color_hex(0x9B9797), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_power3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_power3, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -70 );
lv_obj_set_y( ui_Label2, 78 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"POWER");

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 43 );
lv_obj_set_y( ui_Label3, -59 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"08/09");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 109 );
lv_obj_set_y( ui_Label1, 50 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"14xx");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 43 );
lv_obj_set_y( ui_Label4, 155 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"B4");
lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_Label4, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel8 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel8, 149);
lv_obj_set_height( ui_Panel8, 45);
lv_obj_set_x( ui_Panel8, -99 );
lv_obj_set_y( ui_Panel8, -134 );
lv_obj_set_align( ui_Panel8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel8, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel9 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel9, 81);
lv_obj_set_height( ui_Panel9, 53);
lv_obj_set_x( ui_Panel9, -67 );
lv_obj_set_y( ui_Panel9, 134 );
lv_obj_set_align( ui_Panel9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0xFD0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -76 );
lv_obj_set_y( ui_Label5, -124 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"CONTROLLER");
lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -71 );
lv_obj_set_y( ui_Label6, -143 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"LOCO");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -68 );
lv_obj_set_y( ui_Label7, 122 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"STOP");
lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -61 );
lv_obj_set_y( ui_Label8, 146 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"ALL");
lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -58 );
lv_obj_set_y( ui_Label9, 153 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9," ");
lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x393535), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Panel9, ui_event_Panel9, LV_EVENT_ALL, NULL);
uic_Screen1 = ui_Screen1;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
uic_Screen1= NULL;
ui_Screen1= NULL;
ui_power= NULL;
ui_Arc1= NULL;
ui_Arc2= NULL;
ui_Arc3= NULL;
ui_Arc4= NULL;
ui_power1= NULL;
ui_power2= NULL;
ui_power3= NULL;
ui_Label2= NULL;
ui_Label3= NULL;
ui_Label1= NULL;
ui_Label4= NULL;
ui_Panel8= NULL;
ui_Panel9= NULL;
ui_Label5= NULL;
ui_Label6= NULL;
ui_Label7= NULL;
ui_Label8= NULL;
ui_Label9= NULL;

}
